### ISSUE TITLE
Command not found: test:eval

### ISSUE THREAD

**Issue by SimonScholz** [aqruos/com.acme.prime#1]
Hi,

I don't know whether this is the right place to report my issues with this part of the enroute tutorial http://enroute.osgi.org/tutorial_base/400-run.html

I followed all of the steps twice and still get an error, which says "Command not found: test:eval"

![image](https://cloud.githubusercontent.com/assets/7559962/22395493/a6210ce6-e540-11e6-809b-f05dd5168169.png)

Do you have a clue what might be wrong? If not, I can also upload my code so that you as an expert could have a look. 

This repo contains the whole sample, but not the single steps from the different pages, like 400-run.html. Maybe you could provide the single steps as branches. 

Nice tutorial in general btw.

**Comment by aqruos** [comment]
Hi,

Uploading your code would definetly help. Is the code redeployed after adding changes ? All the required runtime dependencies are there?

**Comment by aqruos** [comment]
Hi again, 
Sorry, for late answer, I am travelling, and Ian in no proximity of a computer  :)
